steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - codegen-webhook
      - --region=us-central1
      - --source=.
      - --entry-point=main
      - --runtime=python310
      - --allow-unauthenticated

timeout: '900s'
