options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/mywebsitebot-dkju/zoni', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/mywebsitebot-dkju/zoni']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'zoni',
        '--image', 'gcr.io/mywebsitebot-dkju/zoni',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]
